### ISSUE TITLE
Support `WebDXFeature` detection in HTTP Archive

### ISSUE THREAD

**Issue by felixarntz** [HTTPArchive/crawl#1]
It would be great if HTTP Archive supported storing the `WebDXFeature` data for each origin (see https://github.com/web-platform-dx/web-features), i.e. for each origin which features from the list it supports.

These features are being recorded for page loads (see [Chromium source list](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojom/use_counter/metrics/webdx_feature.mojom)). So similar to the Chrome use counter data that HTTP Archive already stores in the `features` column of `httparchive.crawl.pages`, it would be great if that table exposed the feature counters.

Potentially the `features` column could be used for this same set of features as well, via a new type e.g. `webdx`?

**Comment by pmeenan** [comment]
Chrome reports a Blink.UseCounter.WebDXFeatures histogram which has a count for each "bucket" (with each bucket presumably being a feature). Somewhere someone is going to have to maintain a mapping between the integer bucket names and the feature names (I'd prefer if we didn't replicate the nightmare that is the current feature mapping).

What mechanism for storing them would be easiest to query?

**Comment by pmeenan** [comment]
We could potentially add the feature mapping to the same sync that is used for the regular platform features - I'd just prefer not to add another fragile point if we don't have to (breaks any time Chrome refactors and moves the enums).

**Comment by pmeenan** [comment]
OK, the webdx features have been added to the features table as type `webdx`. This month's crawl should pick them up.  You can see a preview of ~10 pages in the `crawl_staging` tables which I used for a quick test.

**Comment by felixarntz** [comment]
@pmeenan This is perfect, thank you for implementing this so quickly!

**Comment by tunetheweb** [comment]
Amazing! Thanks @pmeenan !!
